version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/Android"    # ajuste conforme a localização do build.gradle / configurações Android
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"   # se for SPM
    directory: "/iOS"       # ou onde estiver o `Package.swift`
    schedule:
      interval: "weekly"
