name: iOS CI
on:
  push:
    # O workflow será executado em qualquer push para a branch 'main' 
    branches: [ main ]
    # **OPCIONAL:** Execute apenas se houver mudanças no diretório 'iOS/'
    paths:
      - 'iOS/**'
  pull_request:
    # O workflow será executado em qualquer PR para a branch 'main'
    branches: [ main ]
    # **OPCIONAL:** Execute apenas se houver mudanças no diretório 'iOS/'
    paths:
      - 'iOS/**'
  # Permite executar o workflow manualmente na aba "Actions"
  workflow_dispatch:
jobs:
  build-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: List Available Xcode Versions
        run: |
          echo "Verificando versões do Xcode disponíveis:"
          find /Applications/ -name "Xcode*.app" -type d
          echo "Versão atual do Xcode:"
          xcode-select -p
      
      - name: Select Xcode
        run: |
          # Verifica se Xcode_16.app existe, caso contrário usa Xcode.app
          if [ -d "/Applications/Xcode_16.app/Contents/Developer" ]; then
            echo "Selecionando Xcode 16..."
            sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer
          elif [ -d "/Applications/Xcode.app/Contents/Developer" ]; then
            echo "Selecionando Xcode padrão..."
            sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
          else
            echo "Erro: Nenhuma versão do Xcode encontrada!"
            find /Applications/ -name "Xcode*.app" -type d
            exit 1
          fi
          echo "Xcode selecionado:"
          xcode-select -p
      - name: Build & Test (Xcodeproj)
        run: |
          cd iOS
          xcodebuild -project AppDimens.xcodeproj \
            -scheme AppDimens \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
            clean build test | xcpretty
